name: example
description: "A basic Flutter app designed to demonstrate the use of the adaptive_golden_test package."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  golden_variant:
    path: ../

flutter:
  uses-material-design: true
  fonts:
  - family: Roboto
    fonts:
      - asset: fonts/Roboto-Black.ttf
      - asset: fonts/Roboto-BlackItalic.ttf
      - asset: fonts/Roboto-Bold.ttf
      - asset: fonts/Roboto-BoldItalic.ttf
      - asset: fonts/Roboto-Italic.ttf
      - asset: fonts/Roboto-Light.ttf
      - asset: fonts/Roboto-LightItalic.ttf
      - asset: fonts/Roboto-Medium.ttf
      - asset: fonts/Roboto-MediumItalic.ttf
      - asset: fonts/Roboto-Regular.ttf
      - asset: fonts/Roboto-Thin.ttf
      - asset: fonts/Roboto-ThinItalic.ttf
