name: golden_variant
description: "A convenient golden test package that allows you to perform multi-variant test."
version: 0.1.2
repository: https://github.com/cyrax111/golden_variant

environment:
  sdk: ^3.4.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  device_frame_plus: ^1.2.2+1
  package_config: ^2.1.0

dev_dependencies:
  flutter_lints: ^5.0.0


flutter:
